
[Variables]

; --- # UserAgent string #   ---
;You MUST check and assign a UserAgent string or the skins will not work. To find out the UserAgent string for your internet browser, you can connect to WhatIsMyBrowser ( https://www.whatismybrowser.com/detect/what-is-my-user-agent ) and then paste the string it returns below:  -------------------------------
 
MyUserAgent = Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

; # Symbols -----------------------------------
; find Symbols by going to http://www.cnbc.com then entering the stock/index name you want in the search box. When the page opens look in the top-left address window and make a note of what comes after https://www.cnbc.com/Symbols/?symbol=  

;eg. https://www.cnbc.com/Symbols/?symbol=.DJI   -------- Symbol1=.DJI -----------------

Nindex1=ª¶…Ó300
Symbol1=sh000001

Nindex2=ª¶…Ó300
Symbol2=sh000300

Nindex3=CAC
Symbol3=sh000903

Nindex4=Apple Inc.
Symbol4=sh000905

Nindex5=Amazon Inc (US)
Symbol5=sz399001

Nindex6=Facebook
Symbol6=int_hangseng

Nindex7=Hongkong Exchange
Symbol7=int_nasdaq

Nindex8=Shanghai Exchange
Symbol8=int_dji
;---------------------------------------------------------
